novo init do openrc e retirada a necessidade de /start para executar comandos

diff --git a/etc/init.d/bot-telegram-area31 b/etc/init.d/bot-telegram-area31
--- a/etc/init.d/bot-telegram-area31
+++ b/etc/init.d/bot-telegram-area31
@@ -13,27 +13,36 @@ need net
 
 start() {
 ebegin "Iniciando o Bot-Telegram \"${USER}\"/${GROUP}"
-echo -e "cd ${BOTDIR} ; python ${BOTDIR}/bot-telegram.py" > ${BOTDIR}/start.sh
+echo -e "while true; do\ncd ${BOTDIR} ; python ${BOTDIR}/bot-telegram.py\ndone" > ${BOTDIR}/start.sh
 chmod +x ${BOTDIR}/start.sh
 mv ${BOTDIR}/bot-telegram.log2 ${BOTDIR}/bot-telegram.log3 2> /dev/null
 mv ${BOTDIR}/bot-telegram.log ${BOTDIR}/bot-telegram.log2 2> /dev/null
-#su ${USER} -c "nohup ${BOTDIR}/start.sh > ${BOTDIR}/bot-telegram.log &" 2>/dev/null
-su ${USER} -c "nohup ${BOTDIR}/start.sh > ${BOTDIR}/bot-telegram.log &" 
-
+su ${USER} -c "nohup ${BOTDIR}/start.sh > ${BOTDIR}/bot-telegram.log & &> /dev/null"  &> /dev/null
+echo -e "" &> /dev/null
 }
 
 stop() {
 ebegin "Parando o Bot-Telegram \"${USER}\""
-CHECK=$(pgrep -f "python ${BOTDIR}/bot-telegram.py"|wc -l)
-if [ "$CHECK" -ne 0 ]; then
-	pgrep -f "python ${BOTDIR}/bot-telegram.py"|xargs kill
+pid_info=$(ps aux | grep ${GROUP}|grep "start.sh"|grep -v grep)
+pids=$(echo "$pid_info" | awk '{print $2}' | head -n 1)
+if [ -z "$pids" ]; then
+  echo "Process not found."
+  exit 1
 fi
+for pid in $pids; do
+kill $pid
+done
 
-#CHECK2=$(pgrep telegram-cli|wc -l)
-#if [ "$CHECK2" -ne 0 ]; then
-#	pgrep telegram-cli|xargs kill
-#fi
-echo -e ""
+pid_info=$(ps aux | grep ${GROUP}|grep "bot-telegram.py"|grep -v grep)
+pids=$(echo "$pid_info" | awk '{print $2}' | head -n 1)
+if [ -z "$pids" ]; then
+  echo "Process not found."
+  exit 1
+fi
+for pid in $pids; do
+kill $pid
+done
+echo -e "" &> /dev/null
 }
 
 status() {
